#!/usr/bin/env python


import html.parser
import sys

import markdown


styles = {
    "div.wrapper": "max-width: 45em; color: darkblue; font-size: 1.1em; font-family: sans",
    "li": "margin-bottom: 0.5em;",
    "p": "margin-bottom: 1em;",
    "ul": "margin-bottom: 1em;",
}


def print_element(tag, selector=None):
    if selector is None:
        selector = tag
    print('<%s style="%s">' % (tag, styles[selector]))


class EbayFormattingParser(html.parser.HTMLParser):
    def handle_starttag(self, tag, attrs):
        if tag in styles.keys():
            print_element(tag)
        else:
            attr_text = " ".join(['%s="%s"' % (k, v) for k, v in attrs])
            print("<" + " ".join((tag, attr_text)).strip() + ">")

    def handle_endtag(self, tag):
        print("</%s>" % tag)

    def handle_data(self, data):
        print(data.strip())


if __name__ == "__main__":
    text = sys.stdin.read()
    markup = markdown.markdown(text)
    print_element("div", "div.wrapper")
    parser = EbayFormattingParser()
    parser.feed(markup)
    parser.close()
    print("</div>")
